version: '3.3'

services:
  web:
    container_name: dechat-app-container.prod
    image: dechat-app.prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
    environment:
      - PORT=80