#Stage 1
FROM node:11.9.0-alpine as node

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build:docker

#Stage 2
FROM nginx:alpine

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

RUN rm -rf /usr/share/nginx/html/*

COPY --from=node /app/dist /usr/share/nginx/html

COPY --from=node /app/entrypoint.sh /usr/share/nginx/

RUN chmod +x /usr/share/nginx/entrypoint.sh

CMD ["/bin/sh", "/usr/share/nginx/entrypoint.sh"]
