[[section-introduction-and-goals]]
=== Introduction and Goals

****
The development will consist of a WebApp whose objective is to be a decentralized chat, using SOLID technologies. This chat will allow users to exchange messages in different formats (audio, text, video), as well as other functions such as: share screen or video call; It will also allow you to save friends lists, show notifications, among other functions. It will be a web application developed at Angular, and an RDF library will be used to communicate and obtain information on the different PODs
****

=== Requirements Overview

****
The application will mainly comply with the following:

•	The system will be based on a decentralized architecture where data storage is separated from the app
•	Users can store their chat data in their own pods
•	The app will allow a user to share pictures, videos or other kinds of files with other friends through the chat
•	A user can get notifications when some friend wants to chat with him
•	Users can have groups of friends with whom they may want to chat
•	It will be possible to have group chats where all members receive the messages 
•	Users can have live calls and videos
•	Users can share their screens in the chat

****

=== Quality Goals

****
The main Stakeholders of this application are Inrupt and users, I will list the most important quality goals for them:

• Usability : Ease of use by non-technical people.
• Responsiveness : The application must send messages in real time.
• Privacy: The application must keep the data private (this is what solid is based on, each one owns their data).
• Security: The application must be secure, users must know who they are talking to and who has access to the chat.
****

=== Stakeholders

****
Stakeholders of the system:

* Developers
* Professor
* Users
* Inrupt

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| Developer |link:https://github.com/Lamasape[Laura Sanchez]| Have to work with the architecture or with code, documentation of the architecture,have to come up with decisions about the system or its development
| Developer | link:https://github.com/enriquefdez5[Enrique Fernandez] | Have to work with the architecture or with code, documentation of the architecture,have to come up with decisions about the system or its development
| Developer | link:https://github.com/joseluisbugallo[Jose Luis Bugallo] | Have to work with the architecture or with code, documentation of the architecture,have to come up with decisions about the system or its development
| Developer | link:https://github.com/Naive96[Victor Manuel Chaves] | Have to work with the architecture or with code, documentation of the architecture,have to come up with decisions about the system or its development
| Developer |link:https://github.com/golmenero[Carlos Gomez]| Have to work with the architecture or with code, documentation of the architecture,have to come up with decisions about the system or its development
| Developer |link:https://github.com/danielferromeral[Daniel Fernandez] | Have to work with the architecture or with code, documentation of the architecture,have to come up with decisions about the system or its development https://forum.solidproject.org/u/danielferromeral/activity
| Professor | link:https://github.com/labra[Jose Emilio Labra]| Evaluate and guide the project
| Users | | Users can chat,they can have live calls and videos and they can share their screens in the chat
| Inrupt |link:https://inrupt.com/[Inrupt]| They has been proposed as a challenge
|===
****
