[[section-solution-strategy]]
== Solution Strategy

=== Technology and IDE
The team had to choose between betweet new technologies for us and technologies already kown but that dd no have as much suport to SOLID. Based on what we knew, our first option was to choose Java as programming language, but after reading the SOLID documentation, we decided to choose JavaScript, more specifically, the Angular Framework.

About the IDE, we choose WebStorm due to its power and the fact that, as students, we have a free payment license. In addition, some of the members of the group have used it in previous subjects.

=== Architectural pattern
We decided to use the architectural pattern model-view-controller (MVC) because it is a pattern that gives us more extensibility and maintainability. Also, its implementation supports rapid and parallel development.
For more information visit: https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller

=== Methodology of work
We will use Scrum to develope this project. Scrum can provide us an early software development, and more independence when programming. Our project will start implementing the basic functions of a chat and it will grow in complexity (https://en.wikipedia.org/wiki/Scrum_(software_development))
