[[section-deployment-view]]


== Deployment View

[role="arc42help"]
****
*¿What hardware do you need to use the application?*

Fortunately, to use the application you just need one computer connected to Internet. You can also use a mobile phone to chat with your friends, but we haven´t developed the app specyfically to be used on it, so there will be some problems. We are working hard to try to make it more comfortable for mobile users.

At this point of the development, there is no need for geographical permissions or others like that, so the only thing you need is a computer and an Internet connection.

Although, this is an early version of the project, and it hasn´t been optimized yet, so you´ll need some available RAM in your computer, but not too much for worrying about it.

We developed this app mostly in Google Chrome and Firefox, so we recommend this browser.


*Mapping of relationship between hardware and software*

The relationship between software and hardware is very simple, there are three main components that need special attention:

* Computer.

* Browser: As we said before, we recommend Google Chrome and Firefox. Browser connects to the application.

* Application: It connects to server.

* Server: Automatically synchronizes with solid server.

It is important to notice that talking about resources *the application consumes the same resources as another app*, because it is launched in a browser.

****
