[[section-technical-risks]]
== Risks and Technical Debts
.Contents
A list of identified technical risks or technical debts, ordered by priority

.Motivation
“Risk management is project management for grown-ups” (Tim Lister, Atlantic Systems Guild.) 

This should be your motto for systematic detection and evaluation of risks and technical debts in the architecture, which will be needed by management stakeholders (e.g. project managers, product owners) as part of the overall risk analysis and measurement planning.

.Form
List of risks and/or technical debts, probably including suggested measures to minimize, mitigate or avoid risks or reduce technical debts.

[width="100%",frame="topbot",options="header", cols=".^5,2"]
|==
| Risks|Solutions                                                    
| Lack of knowledge and use of angularjs a|
* Consult forums
* Look at the documentation
* take courses
| Lack of knowledge of solid a|* Look at the solid forums
* Ask other classmates               	
|Abandonment / lack of work of a member a|* Know the status of the entire project
* Hold periodic meetings	
|Lack of time to complete the project a| * Do it stepwise and continue
|Misunderstood the requirements of the application a| * Consult with the professor about the requirements            	
|Problems with git a| * Use a specific methodology to do merges and commits 
|==
