[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

[role="arc42help"]
****
Stakeholders of the system:

* Developers
* Professor
* Users
* Inrupt

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| Developers |link:https://github.com/Lamasape[Laura Sanchez]| Have to work with the architecture or with code, documentation of the architecture,have to come up with decisions about the system or its development
| Developers | link:https://github.com/enriquefdez5[Enrique Fernandez] | Have to work with the architecture or with code, documentation of the architecture,have to come up with decisions about the system or its development
| Developers | link:https://github.com/joseluisbugallo[Jose Luis Bugallo] | Have to work with the architecture or with code, documentation of the architecture,have to come up with decisions about the system or its development
| Developers | link:https://github.com/Naive96[Victor Manuel Chaves] | Have to work with the architecture or with code, documentation of the architecture,have to come up with decisions about the system or its development
| Developers |link:https://github.com/golmenero[Carlos Gomez]| Have to work with the architecture or with code, documentation of the architecture,have to come up with decisions about the system or its development
| Developers | _<Contact-2>_ | Have to work with the architecture or with code, documentation of the architecture,have to come up with decisions about the system or its development
| Professor | link:https://github.com/labra[Jose Emilio Labra]| Evaluate and guide the project
| Users | _<Contact-2>_ | Users can chat,they can have live calls and videos and they can share their screens in the chat
| Inrupt |link:https://inrupt.com/[Inrupt]| The assignment has been proposed as a challenge
|===
