[[section-design-decisions]]
== Design Decisions

* First decision is that we are using Git as version control system instead of using mercurial, vsn, etc. and GitHub as source code management instead of using Bitbucket, this decision was imposed by the teachers of the subject.
* We are using javascript family language(javascript, typescript, node.js, angular, etc) to build the application as the main programming language. As we understand, javascript is the easiest way to make a SOLID application.
* We are also using basic languages for the web such as html, css, etc.
* Social linked data(SOLID) based application. A must decision we have to follow if we want to make a decentralized application. This means following several important constraints to build the application. One of them is storing date in PODS, so the user is the owner of their data.
* Following MVC architecture as much as we can. It is the main architecture model we know something about, so we are going to try to follow it as much as we can.
* Following Angular components structure, so we can build a high cohesion and low coupling app.
* To be continued.


===== TODO Improve Mind-Map
===== TODO Full decisions table?
